/**
 * 默认数据
 * 包含常见食材和营养数据
 */

import { Ingredient, IngredientCategory, Cat, LifeStage, ActivityLevel } from '../types';

/**
 * 默认食材库
 * 数据来源: USDA FoodData Central, NRC 2006
 */
export const defaultIngredients: Ingredient[] = [
  // ========== 白肉 ==========
  {
    id: 'chicken_breast',
    name: '鸡胸肉',
    category: IngredientCategory.WHITE_MEAT,
    nutritionPer100g: {
      protein: 23.1,
      fat: 1.2,
      carbohydrate: 0,
      fiber: 0,
      moisture: 74.0,
      ash: 1.0,
      calcium: 5,
      phosphorus: 210,
      magnesium: 28,
      potassium: 256,
      sodium: 37,
      taurine: 50,
      omega_3: 0.02,
      omega_6: 0.2,
    },
    ediblePortion: 0.99,
    pricePerKg: 25,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'chicken_thigh',
    name: '鸡腿肉',
    category: IngredientCategory.WHITE_MEAT,
    nutritionPer100g: {
      protein: 19.8,
      fat: 8.8,
      carbohydrate: 0,
      fiber: 0,
      moisture: 70.0,
      ash: 1.0,
      calcium: 8,
      phosphorus: 180,
      magnesium: 22,
      potassium: 240,
      sodium: 70,
      taurine: 60,
      omega_3: 0.05,
      omega_6: 0.8,
    },
    ediblePortion: 0.99,
    pricePerKg: 22,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // ========== 红肉 ==========
  {
    id: 'beef_lean',
    name: '瘦牛肉',
    category: IngredientCategory.RED_MEAT,
    nutritionPer100g: {
      protein: 22.3,
      fat: 4.2,
      carbohydrate: 0,
      fiber: 0,
      moisture: 72.0,
      ash: 1.0,
      calcium: 6,
      phosphorus: 200,
      magnesium: 21,
      potassium: 318,
      sodium: 55,
      taurine: 40,
      omega_3: 0.03,
      omega_6: 0.3,
    },
    ediblePortion: 0.99,
    pricePerKg: 45,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'pork_tenderloin',
    name: '猪里脊',
    category: IngredientCategory.RED_MEAT,
    nutritionPer100g: {
      protein: 22.8,
      fat: 3.5,
      carbohydrate: 0,
      fiber: 0,
      moisture: 73.0,
      ash: 1.0,
      calcium: 5,
      phosphorus: 220,
      magnesium: 25,
      potassium: 360,
      sodium: 50,
      taurine: 45,
      omega_3: 0.02,
      omega_6: 0.4,
    },
    ediblePortion: 0.99,
    pricePerKg: 35,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'lamb',
    name: '羊肉',
    category: IngredientCategory.RED_MEAT,
    nutritionPer100g: {
      protein: 20.0,
      fat: 15.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 64.0,
      ash: 1.0,
      calcium: 8,
      phosphorus: 180,
      magnesium: 20,
      potassium: 280,
      sodium: 60,
      taurine: 35,
      omega_3: 0.5,
      omega_6: 1.2,
    },
    ediblePortion: 0.99,
    pricePerKg: 55,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'duck_breast',
    name: '鸭胸肉',
    category: IngredientCategory.WHITE_MEAT,
    nutritionPer100g: {
      protein: 19.0,
      fat: 10.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 70.0,
      ash: 1.0,
      calcium: 6,
      phosphorus: 170,
      magnesium: 18,
      potassium: 250,
      sodium: 65,
      taurine: 55,
      omega_3: 0.1,
      omega_6: 1.0,
    },
    ediblePortion: 0.99,
    pricePerKg: 30,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'rabbit',
    name: '兔肉',
    category: IngredientCategory.WHITE_MEAT,
    nutritionPer100g: {
      protein: 21.0,
      fat: 3.5,
      carbohydrate: 0,
      fiber: 0,
      moisture: 74.0,
      ash: 1.0,
      calcium: 12,
      phosphorus: 210,
      magnesium: 19,
      potassium: 330,
      sodium: 40,
      taurine: 50,
      omega_3: 0.4,
      omega_6: 0.8,
    },
    ediblePortion: 0.99,
    pricePerKg: 40,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'turkey',
    name: '火鸡肉',
    category: IngredientCategory.WHITE_MEAT,
    nutritionPer100g: {
      protein: 22.0,
      fat: 2.5,
      carbohydrate: 0,
      fiber: 0,
      moisture: 74.0,
      ash: 1.0,
      calcium: 10,
      phosphorus: 200,
      magnesium: 28,
      potassium: 290,
      sodium: 55,
      taurine: 55,
      omega_3: 0.03,
      omega_6: 0.3,
    },
    ediblePortion: 0.99,
    pricePerKg: 38,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  
  // ========== 内脏 ==========
  {
    id: 'chicken_heart',
    name: '鸡心',
    category: IngredientCategory.ORGAN,
    nutritionPer100g: {
      protein: 15.6,
      fat: 9.3,
      carbohydrate: 0.7,
      fiber: 0,
      moisture: 73.0,
      ash: 1.0,
      calcium: 12,
      phosphorus: 180,
      magnesium: 18,
      potassium: 220,
      sodium: 70,
      taurine: 350,
      omega_3: 0.1,
      omega_6: 1.5,
    },
    ediblePortion: 0.98,
    pricePerKg: 20,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'chicken_liver',
    name: '鸡肝',
    category: IngredientCategory.ORGAN,
    nutritionPer100g: {
      protein: 16.9,
      fat: 4.8,
      carbohydrate: 2.5,
      fiber: 0,
      moisture: 74.0,
      ash: 1.3,
      calcium: 8,
      phosphorus: 280,
      magnesium: 20,
      potassium: 260,
      sodium: 80,
      vitamin_a: 12000,
      vitamin_b2: 2.0,
      vitamin_b12: 16.0,
      taurine: 60,
      omega_3: 0.2,
      omega_6: 0.8,
    },
    ediblePortion: 0.98,
    pricePerKg: 18,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'beef_liver',
    name: '牛肝',
    category: IngredientCategory.ORGAN,
    nutritionPer100g: {
      protein: 20.4,
      fat: 3.6,
      carbohydrate: 5.0,
      fiber: 0,
      moisture: 69.0,
      ash: 1.5,
      calcium: 5,
      phosphorus: 380,
      magnesium: 18,
      potassium: 310,
      sodium: 70,
      vitamin_a: 22000,
      vitamin_b2: 3.0,
      vitamin_b12: 60.0,
      taurine: 50,
      omega_3: 0.1,
      omega_6: 0.5,
    },
    ediblePortion: 0.98,
    pricePerKg: 25,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'chicken_gizzard',
    name: '鸡胗',
    category: IngredientCategory.ORGAN,
    nutritionPer100g: {
      protein: 18.0,
      fat: 3.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 77.0,
      ash: 1.0,
      calcium: 15,
      phosphorus: 160,
      magnesium: 16,
      potassium: 240,
      sodium: 65,
      taurine: 40,
      omega_3: 0.05,
      omega_6: 0.6,
    },
    ediblePortion: 0.98,
    pricePerKg: 22,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'kidney',
    name: '肾脏',
    category: IngredientCategory.ORGAN,
    nutritionPer100g: {
      protein: 16.0,
      fat: 3.5,
      carbohydrate: 0.5,
      fiber: 0,
      moisture: 78.0,
      ash: 1.0,
      calcium: 10,
      phosphorus: 220,
      magnesium: 18,
      potassium: 260,
      sodium: 180,
      vitamin_a: 1400,
      taurine: 80,
      omega_3: 0.1,
      omega_6: 0.5,
    },
    ediblePortion: 0.98,
    pricePerKg: 20,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  
  // ========== 骨骼 ==========
  {
    id: 'chicken_neck',
    name: '鸡脖',
    category: IngredientCategory.BONE,
    nutritionPer100g: {
      protein: 18.0,
      fat: 12.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 65.0,
      ash: 4.0,
      calcium: 1200,
      phosphorus: 600,
      magnesium: 25,
      potassium: 200,
      sodium: 80,
      taurine: 30,
      omega_3: 0.1,
      omega_6: 1.2,
    },
    ediblePortion: 0.75,
    pricePerKg: 12,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'chicken_wing',
    name: '鸡翅',
    category: IngredientCategory.BONE,
    nutritionPer100g: {
      protein: 19.0,
      fat: 14.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 63.0,
      ash: 3.5,
      calcium: 800,
      phosphorus: 450,
      magnesium: 22,
      potassium: 190,
      sodium: 75,
      taurine: 35,
      omega_3: 0.1,
      omega_6: 1.5,
    },
    ediblePortion: 0.80,
    pricePerKg: 18,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'quail',
    name: '鹌鹑(带骨)',
    category: IngredientCategory.BONE,
    nutritionPer100g: {
      protein: 20.0,
      fat: 8.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 68.0,
      ash: 3.0,
      calcium: 600,
      phosphorus: 350,
      magnesium: 20,
      potassium: 220,
      sodium: 70,
      taurine: 45,
      omega_3: 0.2,
      omega_6: 1.0,
    },
    ediblePortion: 0.85,
    pricePerKg: 28,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  
  // ========== 营养添加剂 ==========
  {
    id: 'egg_yolk',
    name: '蛋黄',
    category: IngredientCategory.SUPPLEMENT,
    nutritionPer100g: {
      protein: 15.9,
      fat: 26.5,
      carbohydrate: 0.7,
      fiber: 0,
      moisture: 48.0,
      ash: 1.0,
      calcium: 129,
      phosphorus: 390,
      magnesium: 12,
      potassium: 110,
      sodium: 120,
      vitamin_a: 520,
      vitamin_d: 80,
      vitamin_e: 2.7,
      vitamin_b12: 2.0,
      taurine: 20,
      omega_3: 0.4,
      omega_6: 3.0,
    },
    ediblePortion: 1.0,
    pricePerKg: 15,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'fish_oil',
    name: '鱼油',
    category: IngredientCategory.SUPPLEMENT,
    nutritionPer100g: {
      protein: 0,
      fat: 100.0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 0,
      ash: 0,
      calcium: 0,
      phosphorus: 0,
      magnesium: 0,
      potassium: 0,
      sodium: 0,
      vitamin_d: 10000,
      vitamin_e: 15.0,
      omega_3: 30.0,
      omega_6: 2.0,
    },
    ediblePortion: 1.0,
    pricePerKg: 80,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'calcium_carbonate',
    name: '碳酸钙粉',
    category: IngredientCategory.SUPPLEMENT,
    nutritionPer100g: {
      protein: 0,
      fat: 0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 0,
      ash: 100.0,
      calcium: 40000,
      phosphorus: 0,
      magnesium: 0,
      potassium: 0,
      sodium: 0,
    },
    ediblePortion: 1.0,
    pricePerKg: 30,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'vitamin_e',
    name: '维生素E',
    category: IngredientCategory.SUPPLEMENT,
    nutritionPer100g: {
      protein: 0,
      fat: 0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 0,
      ash: 0,
      calcium: 0,
      phosphorus: 0,
      magnesium: 0,
      potassium: 0,
      sodium: 0,
      vitamin_e: 1000.0,
    },
    ediblePortion: 1.0,
    pricePerKg: 150,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'taurine',
    name: '牛磺酸粉',
    category: IngredientCategory.SUPPLEMENT,
    nutritionPer100g: {
      protein: 0,
      fat: 0,
      carbohydrate: 0,
      fiber: 0,
      moisture: 0,
      ash: 0,
      calcium: 0,
      phosphorus: 0,
      magnesium: 0,
      potassium: 0,
      sodium: 0,
      taurine: 100000,
    },
    ediblePortion: 1.0,
    pricePerKg: 200,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'kelp_powder',
    name: '海带粉(碘来源)',
    category: IngredientCategory.SUPPLEMENT,
    nutritionPer100g: {
      protein: 7.0,
      fat: 1.0,
      carbohydrate: 50.0,
      fiber: 30.0,
      moisture: 10.0,
      ash: 25.0,
      calcium: 1680,
      phosphorus: 220,
      magnesium: 760,
      potassium: 7600,
      sodium: 2500,
      vitamin_a: 250,
      vitamin_e: 5.0,
    },
    ediblePortion: 1.0,
    pricePerKg: 60,
    isDefault: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

/**
 * 示例猫咪
 */
export const sampleCats: Cat[] = [
  {
    id: 'cat_1',
    name: '咪咪',
    weight: 4.5,
    lifeStage: LifeStage.ADULT,
    activityLevel: ActivityLevel.MODERATE,
    isNeutered: true,
    targetBodyCondition: 'ideal',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

/**
 * 获取默认食材
 */
export function getDefaultIngredients(): Ingredient[] {
  return defaultIngredients.map(ing => ({
    ...ing,
    id: `${ing.id}_${Date.now()}`,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }));
}

/**
 * 获取示例猫咪
 */
export function getSampleCats(): Cat[] {
  return sampleCats.map(cat => ({
    ...cat,
    id: `cat_${Date.now()}`,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  }));
}

/**
 * 经典配方模板
 * 基于生骨肉喂养经验配方
 */
export interface RecipeTemplate {
  id: string;
  name: string;
  description: string;
  ingredients: Array<{
    ingredientId: string;
    weightPercent: number;
  }>;
  isDefault: boolean;
}

export const recipeTemplates: RecipeTemplate[] = [
  {
    id: 'template_1',
    name: '经典鸡牛配方',
    description: '适合成猫的基础配方，蛋白质丰富，营养均衡。鸡肉提供易消化蛋白，牛肉补充铁质。',
    ingredients: [
      { ingredientId: 'chicken_breast', weightPercent: 40 },
      { ingredientId: 'chicken_thigh', weightPercent: 15 },
      { ingredientId: 'beef_lean', weightPercent: 20 },
      { ingredientId: 'chicken_heart', weightPercent: 10 },
      { ingredientId: 'chicken_liver', weightPercent: 5 },
      { ingredientId: 'chicken_neck', weightPercent: 8 },
      { ingredientId: 'egg_yolk', weightPercent: 2 },
    ],
    isDefault: true,
  },
  {
    id: 'template_2',
    name: '鸡鸭双拼配方',
    description: '白肉为主的温和配方，适合肠胃敏感的猫咪。鸭肉清热，适合夏季食用。',
    ingredients: [
      { ingredientId: 'chicken_breast', weightPercent: 35 },
      { ingredientId: 'duck_breast', weightPercent: 25 },
      { ingredientId: 'chicken_heart', weightPercent: 10 },
      { ingredientId: 'chicken_liver', weightPercent: 5 },
      { ingredientId: 'chicken_wing', weightPercent: 10 },
      { ingredientId: 'egg_yolk', weightPercent: 2 },
      { ingredientId: 'fish_oil', weightPercent: 0.5 },
    ],
    isDefault: true,
  },
  {
    id: 'template_3',
    name: '幼猫成长配方',
    description: '高蛋白高脂肪配方，满足幼猫快速生长发育需求。牛磺酸充足，促进视力和心脏健康。',
    ingredients: [
      { ingredientId: 'chicken_breast', weightPercent: 30 },
      { ingredientId: 'chicken_thigh', weightPercent: 20 },
      { ingredientId: 'beef_lean', weightPercent: 15 },
      { ingredientId: 'chicken_heart', weightPercent: 15 },
      { ingredientId: 'chicken_liver', weightPercent: 8 },
      { ingredientId: 'chicken_neck', weightPercent: 8 },
      { ingredientId: 'egg_yolk', weightPercent: 3 },
      { ingredientId: 'fish_oil', weightPercent: 0.5 },
    ],
    isDefault: true,
  },
  {
    id: 'template_4',
    name: '兔肉低敏配方',
    description: '低敏配方，适合对常见肉类过敏的猫咪。兔肉高蛋白低脂肪，易消化吸收。',
    ingredients: [
      { ingredientId: 'rabbit', weightPercent: 45 },
      { ingredientId: 'chicken_breast', weightPercent: 20 },
      { ingredientId: 'chicken_heart', weightPercent: 10 },
      { ingredientId: 'beef_liver', weightPercent: 5 },
      { ingredientId: 'quail', weightPercent: 10 },
      { ingredientId: 'egg_yolk', weightPercent: 2 },
      { ingredientId: 'fish_oil', weightPercent: 0.5 },
    ],
    isDefault: true,
  },
  {
    id: 'template_5',
    name: '老年猫养护配方',
    description: '低脂肪配方，适合老年猫和需要控制体重的猫咪。添加关节保护成分。',
    ingredients: [
      { ingredientId: 'chicken_breast', weightPercent: 45 },
      { ingredientId: 'turkey', weightPercent: 20 },
      { ingredientId: 'chicken_heart', weightPercent: 10 },
      { ingredientId: 'chicken_liver', weightPercent: 5 },
      { ingredientId: 'chicken_neck', weightPercent: 10 },
      { ingredientId: 'egg_yolk', weightPercent: 2 },
      { ingredientId: 'kelp_powder', weightPercent: 0.3 },
    ],
    isDefault: true,
  },
];

/**
 * 根据模板创建配方
 * @param template 配方模板
 * @param totalWeight 总重量(g)
 * @returns 配方食材列表
 */
export function createRecipeFromTemplate(
  template: RecipeTemplate,
  totalWeight: number
): Array<{ ingredientId: string; weight: number }> {
  return template.ingredients.map(item => ({
    ingredientId: item.ingredientId,
    weight: Math.round((totalWeight * item.weightPercent) / 100),
  }));
}
